version: '3.7'
services:

  backend:
    image: ${DOCKER_IMAGE:-gitcloud-backend}:${DOCKER_VERSION:-latest}
    container_name: gitcloud_backend_48080
    ports:
      - ${GITCLOUD_BACKEND_PORT}:${GITCLOUD_BACKEND_PORT}
    environment:
      - GITCLOUD_BACKEND_PORT=${GITCLOUD_BACKEND_PORT}
    restart: always
    stdin_open: true
    tty: true

  