version: '3.7'
services:

  backend:
    image: ${DOCKER_IMAGE:-gitcloud-backend}:${DOCKER_VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GITCLOUD_BACKEND_RELEASE_AUTH=${GITCLOUD_BACKEND_RELEASE_AUTH}